kind: pipeline
type: docker

trigger:
  paths:
    include:
      - repo1/*  

steps:
  - name: step1
    image: nginx
    commands:
      - echo "repo1 changed"

  - name: step2
    image: nginx
    commands:
      - echo "repo1 changed"
